const tags = [
    "MOVIE", "HORROR", "SCIFI", "TECH", "TRAVEL", "LIFESTYLE", "HEALTH", "FITNESS",
    "EDUCATION", "BUSINESS", "FINANCE", "ENTERTAINMENT", "FOOD", "ART", "DESIGN",
    "MUSIC", "WRITING", "PERSONAL_DEVELOPMENT", "PRODUCTIVITY", "PHOTOGRAPHY",
    "MARKETING", "SPORTS", "POLITICS", "ENVIRONMENT", "SPIRITUALITY", "HISTORY",
    "GAMING", "PARENTING", "SCIENCE", "NATURE", "FASHION", "DIY", "CAREER",
    "SOCIAL_MEDIA", "BOOKS", "STARTUPS", "PSYCHOLOGY", "SELF_IMPROVEMENT",
    "MENTAL_HEALTH", "NEWS", "MEMES", "ANIME", "CULTURE"
];

export default tags;
